# Trenowanie tensorów

In [43]:
import tensorflow as tf
import numpy as np

In [59]:
tensor_idx = tf.constant([1.23, 10.65])

In [54]:
tensor_idx[..., 2:5]

<tf.Tensor: shape=(0,), dtype=float32, numpy=array([], dtype=float32)>

In [46]:
tab = np.zeros(shape=(3,4,5))

In [47]:
tf.convert_to_tensor(tab)

<tf.Tensor: shape=(3, 4, 5), dtype=float64, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])>

In [57]:
tf.math.cos(tensor_idx)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.33423772, -0.33873743], dtype=float32)>

In [60]:
tf.math.argmax(tensor_idx)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [79]:
B = tf.constant([[2, 20, 30, 3, 6], 
                 [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])


In [80]:
print(tf.math.argmax(B, axis=0))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
